# Stuff for regular Iguana build.
Import("env")
if env.test_lib == 'mutex':
    env["EXPECT_TEST_DATA"] = [("100%: Checks: 2, Failures: 0, Errors: 0", None)]
lib = env.KengeLibrary("mutex", LIBS=[])
Return("lib")
