#
# Generated by the NeXT Project Builder.
#
# NOTE: Do NOT change this file -- Project Builder maintains it.
#
# Put all of your customizations in files called Makefile.preamble
# and Makefile.postamble (both optional), and Makefile will include them.
#

NAME = streams

PROJECTVERSION = 2.8
PROJECT_TYPE = Library

HFILES = defs.h streams.h streamsextra.h streamsimpl.h

CFILES = except.c file_funcs.c globals.c indir_ops.c ipc_funcs.c\
         memory_funcs.c NXLogError.c streams.c streams_doprnt.c\
         streams_doscan.c streams_internal.c

OTHERSRCS = Makefile.preamble Makefile Makefile.postamble


MAKEFILEDIR = $(MAKEFILEPATH)/pb_makefiles
CURRENTLY_ACTIVE_VERSION = YES
DEPLOY_WITH_VERSION_NAME = A
CODE_GEN_STYLE = DYNAMIC
MAKEFILE = library.make
NEXTSTEP_INSTALLDIR = /usr/local/lib/system
WINDOWS_INSTALLDIR = /Developer/Libraries
PDO_UNIX_INSTALLDIR = /Local/Developer/Libraries
LIBS = 
DEBUG_LIBS = $(LIBS)
PROF_LIBS = $(LIBS)


HEADER_PATHS = -I$(HDRROOT)$(PUBLIC_HEADER_DIR)\
               -I$(HDRROOT)$(PUBLIC_HEADER_DIR)/bsd\
               -I$(HDRROOT)$(PUBLIC_HEADER_DIR)/bsd/sys\
               -I$(HDRROOT)$(PUBLIC_HEADER_DIR)/bsd/sys/machine\
               -I$(SYMROOT)/PrivateHeaders -I$(SYMROOT)/Headers



NEXTSTEP_PUBLIC_HEADERS_DIR = $(LOCAL_DEVELOPER_DIR)/Headers/$(NAME)

WINDOWS_PUBLIC_HEADERS_DIR = $(HOMEDRIVE)$(LOCAL_DEVELOPER_DIR)/Headers/$(NAME)

PDO_UNIX_PUBLIC_HEADERS_DIR = $(LOCAL_DEVELOPER_DIR)/Headers/$(NAME)

NEXTSTEP_OBJCPLUS_COMPILER = /usr/bin/cc
WINDOWS_OBJCPLUS_COMPILER = $(DEVDIR)/gcc
PDO_UNIX_OBJCPLUS_COMPILER = $(NEXTDEV_BIN)/gcc
NEXTSTEP_JAVA_COMPILER = /usr/bin/javac
WINDOWS_JAVA_COMPILER = $(JDKBINDIR)/javac.exe
PDO_UNIX_JAVA_COMPILER = $(JDKBINDIR)/javac

include $(MAKEFILEDIR)/platform.make

-include Makefile.preamble

include $(MAKEFILEDIR)/$(MAKEFILE)

-include Makefile.postamble

-include Makefile.dependencies
