
FILES=main.cpp malloc_test.cpp


all: 
	@echo "Hello! This is an arbitrary test."
	@echo 
	@echo "Usage: make [ clean | linux ]"
	@echo 


clean:
	rm -f ./*.o
	rm -f ./mtest

linux:
	g++  -I../ $(FILES) -o mtest
	rm -rf ./*.o




